services:
  inventory_app:
    container_name: inventory_app
    build: .
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=jdbc:postgresql://inventory_db:5432/GestorInventarios
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=magic
    depends_on:
      - inventory_db
    working_dir: /app
    command: mvn spring-boot:run

  inventory_db:
    container_name: inventory_db
    image: postgres:12
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: magic
      POSTGRES_DB: GestorInventarios
  inventory_app_test:
    container_name: inventory_app_test
    image: maven:3.8.4-openjdk-17-slim
    working_dir: /app
    volumes:
      - .:/app
    depends_on:
      - inventory_db
    command: mvn test