name: Run Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-deploy:
    name: build and deploy spring-api
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 22
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '22'
          cache: 'maven'

      - name: Build with Maven
        run: mvn clean install
      - name: Run docker-compose
          uses: hoverkraft-tech/compose-action@v2.0.1
          with:
            compose-file: ".docker-compose.yml"

            - name: Execute tests in the running services
              run: |
                docker-compose exec inventoryapp-app